apiVersion: v1
kind: Service
metadata:
  # this the metadata for the service 
  name: bank-note-api-on-kubernetes-service
spec:
  type: ClusterIP
  ports:
    - port: 5000
  selector:
    app: bank-note-api-on-kubernetes

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-note-api-on-kubernetes-deployment

### overall metadata for a cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      ## pod name 
      app: bank-note-api-on-kubernetes
  template:
    metadata:
      labels:
        app: bank-note-api-on-kubernetes
### pod level metadata
    spec: 
      containers:
        - name:  bank-note-api-on-kubernetes-container
          image: docker.io/sairamdgr8/bank-note-api-on-kubernetes
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP




              